"""RM-07: what leaves the robot, from a packet capture.

Reads a pcap (``tcpdump -w``) or pcapng file with no third-party parser,
keeps the connections the robot itself opened, groups them by destination
and port, and labels each against the design's allowed list
(``docs/dev/design-reachy-mini-2026-09-27.md`` section 8). Anything not on
the list fails the check. The privacy page's "what leaves the robot" rows
are rendered here too, so the page cannot drift from the list.

Names come from the capture itself: DNS answers and TLS server names. A
destination with neither is shown by address.
"""

from __future__ import annotations

import difflib
import ipaddress
import re
import select
import signal
import socket
import struct
import subprocess
import threading
import time
from collections.abc import Callable, Iterable
from dataclasses import dataclass, field
from pathlib import Path

PAGE_BEGIN = "<!-- egress-table:begin (generated by scripts/measure_rm07_egress.py) -->"
PAGE_END = "<!-- egress-table:end -->"

_LINK_ETHERNET, _LINK_RAW_BSD, _LINK_RAW, _LINK_LINUX_SLL = 1, 12, 101, 113


@dataclass(frozen=True)
class Packet:
    ts: float
    proto: str  # "tcp", "udp" or "icmp"
    src: str
    sport: int
    dst: str
    dport: int
    length: int  # bytes on the wire as captured, link header included
    flags: int = 0
    payload: bytes = b""


# --- reading captures -------------------------------------------------------


@dataclass
class CaptureDiagnostics:
    ignored_fragments: int = 0


def read_pcap(
    source: bytes | Path | str, *, diagnostics: CaptureDiagnostics | None = None
) -> list[Packet]:
    data = source if isinstance(source, bytes) else Path(source).read_bytes()
    if len(data) >= 4 and data[:4] == b"\x0a\x0d\x0d\x0a":
        frames = _pcapng_frames(data)
    elif len(data) >= 24 and data[:4] in _PCAP_MAGICS:
        frames = _pcap_frames(data)
    else:
        raise ValueError("not a pcap or pcapng file")
    packets = []
    for ts, linktype, frame in frames:
        packet = _decode(ts, linktype, frame, diagnostics=diagnostics)
        if packet is not None:
            packets.append(packet)
    return packets


_PCAP_MAGICS = {
    b"\xd4\xc3\xb2\xa1": ("<", 1e-6),
    b"\xa1\xb2\xc3\xd4": (">", 1e-6),
    b"\x4d\x3c\xb2\xa1": ("<", 1e-9),
    b"\xa1\xb2\x3c\x4d": (">", 1e-9),
}


def _pcap_frames(data: bytes) -> Iterable[tuple[float, int, bytes]]:
    order, scale = _PCAP_MAGICS[data[:4]]
    linktype = struct.unpack(order + "I", data[20:24])[0]
    pos = 24
    while pos + 16 <= len(data):
        sec, frac, caplen, _orig = struct.unpack(order + "IIII", data[pos : pos + 16])
        pos += 16
        if pos + caplen > len(data):
            return  # a capture cut off mid-packet: keep what is whole
        yield sec + frac * scale, linktype, data[pos : pos + caplen]
        pos += caplen


def _pcapng_frames(data: bytes) -> Iterable[tuple[float, int, bytes]]:
    order = "<" if data[8:12] == b"\x4d\x3c\x2b\x1a" else ">"
    pos, links = 0, []
    while pos + 12 <= len(data):
        kind, total = struct.unpack(order + "II", data[pos : pos + 8])
        if total < 12 or pos + total > len(data):
            return
        body = data[pos + 8 : pos + total - 4]
        if kind == 1:
            links.append(struct.unpack(order + "H", body[:2])[0])
        elif kind == 6 and len(body) >= 20:
            iface, hi, lo, caplen, _orig = struct.unpack(order + "IIIII", body[:20])
            if iface < len(links) and 20 + caplen <= len(body):
                yield ((hi << 32 | lo) / 1e6, links[iface], body[20 : 20 + caplen])
        pos += total


def _decode(
    ts: float, linktype: int, frame: bytes, *, diagnostics: CaptureDiagnostics | None = None
) -> Packet | None:
    if linktype == _LINK_ETHERNET:
        if len(frame) < 14:
            return None
        ethertype, offset = struct.unpack("!H", frame[12:14])[0], 14
        while ethertype in (0x8100, 0x88A8) and len(frame) >= offset + 4:
            ethertype = struct.unpack("!H", frame[offset + 2 : offset + 4])[0]
            offset += 4
        ip = frame[offset:]
    elif linktype == _LINK_LINUX_SLL:
        if len(frame) < 16:
            return None
        ethertype, ip = struct.unpack("!H", frame[14:16])[0], frame[16:]
    elif linktype in (_LINK_RAW, _LINK_RAW_BSD):
        ethertype, ip = (0x0800 if frame[:1] and frame[0] >> 4 == 4 else 0x86DD), frame
    else:
        return None
    if ethertype == 0x0800:
        parsed = _ipv4(ip, diagnostics=diagnostics)
    elif ethertype == 0x86DD:
        parsed = _ipv6(ip, diagnostics=diagnostics)
    else:
        return None
    if parsed is None:
        return None
    src, dst, proto, transport = parsed
    return _transport(ts, len(frame), src, dst, proto, transport)


def _ipv4(ip: bytes, *, diagnostics: CaptureDiagnostics | None = None):
    if len(ip) < 20 or ip[0] >> 4 != 4:
        return None
    ihl = (ip[0] & 0x0F) * 4
    fragment_field = struct.unpack("!H", ip[6:8])[0]
    if fragment_field & (0x2000 | 0x1FFF):
        if diagnostics is not None:
            diagnostics.ignored_fragments += 1
        return None  # fragments need reassembly before transport parsing
    return socket.inet_ntoa(ip[12:16]), socket.inet_ntoa(ip[16:20]), ip[9], ip[ihl:]


def _ipv6(ip: bytes, *, diagnostics: CaptureDiagnostics | None = None):
    if len(ip) < 40 or ip[0] >> 4 != 6:
        return None
    src = str(ipaddress.IPv6Address(ip[8:24]))
    dst = str(ipaddress.IPv6Address(ip[24:40]))
    nxt, rest = ip[6], ip[40:]
    while nxt in (0, 43, 60) and len(rest) >= 8:
        nxt, size = rest[0], (rest[1] + 1) * 8
        rest = rest[size:]
    if nxt == 44:
        if diagnostics is not None:
            diagnostics.ignored_fragments += 1
        return None  # fragment headers need reassembly before transport parsing
    return src, dst, nxt, rest


def _transport(ts, length, src, dst, proto, data) -> Packet | None:
    if proto == 6 and len(data) >= 20:
        sport, dport = struct.unpack("!HH", data[:4])
        offset = (data[12] >> 4) * 4
        return Packet(ts, "tcp", src, sport, dst, dport, length, data[13], data[offset:])
    if proto == 17 and len(data) >= 8:
        sport, dport = struct.unpack("!HH", data[:4])
        return Packet(ts, "udp", src, sport, dst, dport, length, 0, data[8:])
    if proto in (1, 58):
        return Packet(ts, "icmp", src, 0, dst, 0, length)
    return None


# --- names from the capture -------------------------------------------------


def _dns_names(packet: Packet) -> dict[str, str]:
    """Address -> queried name, from one DNS response."""
    data = packet.payload
    if packet.proto != "udp" or packet.sport != 53 or len(data) < 12:
        return {}
    flags, qd, an = struct.unpack("!HHH", data[2:8])
    if not flags & 0x8000:
        return {}
    pos, qname = 12, ""
    try:
        for i in range(qd):
            name, pos = _dns_name(data, pos)
            pos += 4
            qname = qname or name
        found = {}
        for _ in range(an):
            _name, pos = _dns_name(data, pos)
            rtype, _cls, _ttl, size = struct.unpack("!HHIH", data[pos : pos + 10])
            pos += 10
            rdata = data[pos : pos + size]
            pos += size
            if rtype == 1 and size == 4:
                found[socket.inet_ntoa(rdata)] = qname
            elif rtype == 28 and size == 16:
                found[str(ipaddress.IPv6Address(rdata))] = qname
        return found
    except (struct.error, IndexError):
        return {}


def _dns_name(data: bytes, pos: int) -> tuple[str, int]:
    labels, end, hops = [], None, 0
    while True:
        length = data[pos]
        if length & 0xC0 == 0xC0:
            if end is None:
                end = pos + 2
            pos = ((length & 0x3F) << 8) | data[pos + 1]
            hops += 1
            if hops > 16:
                raise IndexError("dns pointer loop")
            continue
        pos += 1
        if length == 0:
            return ".".join(labels), (end if end is not None else pos)
        labels.append(data[pos : pos + length].decode("ascii", "replace"))
        pos += length


def _tls_sni(payload: bytes) -> str | None:
    """The server name in a TLS ClientHello, if this payload starts one."""
    try:
        if len(payload) < 48 or payload[0] != 0x16 or payload[5] != 1:
            return None
        pos = 5 + 4 + 2 + 32
        pos += 1 + payload[pos]
        pos += 2 + struct.unpack("!H", payload[pos : pos + 2])[0]
        pos += 1 + payload[pos]
        end = pos + 2 + struct.unpack("!H", payload[pos : pos + 2])[0]
        pos += 2
        while pos + 4 <= end:
            kind, size = struct.unpack("!HH", payload[pos : pos + 4])
            pos += 4
            if kind == 0:
                nlen = struct.unpack("!H", payload[pos + 3 : pos + 5])[0]
                return payload[pos + 5 : pos + 5 + nlen].decode("ascii", "replace").lower()
            pos += size
    except (struct.error, IndexError):
        return None
    return None


# --- grouping ---------------------------------------------------------------


@dataclass
class Group:
    proto: str
    host: str  # a name when the capture names it, else the address
    port: int
    addresses: set[str] = field(default_factory=set)
    flows: int = 0
    packets: int = 0
    bytes_out: int = 0


def group_egress(packets: list[Packet], robot_ip: str) -> list[Group]:
    """Connections the robot opened, grouped by destination and port.

    A connection is the robot's when its first packet in the capture comes
    from the robot; a hub dialling in to the daemon is not egress.
    """
    dns: dict[str, str] = {}
    for p in packets:
        dns.update(_dns_names(p))
    seen: set[tuple] = set()
    flows: dict[tuple, dict] = {}
    for p in packets:
        key = (p.proto, p.src, p.sport, p.dst, p.dport)
        if key in flows:
            flows[key]["packets"] += 1
            flows[key]["bytes"] += p.length
            flows[key]["name"] = flows[key]["name"] or _tls_sni(p.payload)
        elif p.src == robot_ip and (p.proto, p.dst, p.dport, p.src, p.sport) not in seen:
            flows[key] = {"packets": 1, "bytes": p.length, "name": _tls_sni(p.payload)}
        seen.add(key)
    groups: dict[tuple, Group] = {}
    for (proto, _src, _sport, dst, dport), info in flows.items():
        host = info["name"] or dns.get(dst) or dst
        group = groups.setdefault((proto, host, dport), Group(proto, host, dport))
        group.addresses.add(dst)
        group.flows += 1
        group.packets += info["packets"]
        group.bytes_out += info["bytes"]
    return sorted(groups.values(), key=lambda g: (g.host, g.port, g.proto))


# --- the allowed list -------------------------------------------------------


@dataclass(frozen=True)
class HubTarget:
    host: str
    port: int = 443

    @classmethod
    def parse(cls, text: str) -> HubTarget:
        text = text.strip()
        if not text:
            raise ValueError("the hub address is empty")
        match = re.fullmatch(r"\[([^\]]+)\](?::(\d+))?", text)
        if match:
            return cls(match.group(1), int(match.group(2) or 443))
        if text.count(":") == 1:
            host, port = text.split(":")
            return cls(host, int(port))
        return cls(text, 443)


@dataclass(frozen=True)
class AllowedRule:
    id: str
    scope: str  # "hub", "internet" or "local": where the bytes can reach
    what: str
    where: str
    when: str


ALLOWED: tuple[AllowedRule, ...] = (
    AllowedRule(
        "hub",
        "hub",
        "Your MaiPai Home: what you say after the wake word, the robot's state and what it sees",
        "Your hub, on your own network",
        "During a conversation and while the robot is on",
    ),
    AllowedRule(
        "update-check",
        "internet",
        "A software update check",
        "`pypi.org` and `files.pythonhosted.org`",
        "Only when a person clicks it on Home's Updates page, never by itself",
    ),
    AllowedRule(
        "dns",
        "local",
        "Looking up an address by name",
        "Your router or local name server",
        "Whenever the robot needs an address",
    ),
    AllowedRule(
        "mdns",
        "local",
        "Finding your hub and letting it find the robot",
        "Your own network only, never past your router",
        "While the robot is on",
    ),
    AllowedRule(
        "dhcp",
        "local",
        "Asking your router for an address",
        "Your router",
        "When the robot joins your network",
    ),
)
ALLOWED_BY_ID = {rule.id: rule for rule in ALLOWED}

_PYPI_NAMES = {"pypi.org", "files.pythonhosted.org"}
_MDNS = {"224.0.0.251", "ff02::fb"}


@dataclass(frozen=True)
class Row:
    rule: str | None  # the allowed rule's id, None when not on the list
    proto: str
    host: str
    port: int
    flows: int
    packets: int
    bytes_out: int
    addresses: frozenset[str]

    @property
    def listed(self) -> bool:
        return self.rule is not None

    @property
    def scope(self) -> str:
        return ALLOWED_BY_ID[self.rule].scope if self.rule else "internet"


# The household's own network. 192.0.2.0/24 is here because this repo's docs and tests use it
# as the placeholder LAN; 198.51.100.0/24 and 203.0.113.0/24 stand in for the internet.
_LOCAL_NETS = tuple(
    ipaddress.ip_network(n)
    for n in ("10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "192.0.2.0/24", "fc00::/7")
)


def _is_private(address: str) -> bool:
    try:
        ip = ipaddress.ip_address(address)
    except ValueError:
        return False
    return (
        ip.is_loopback
        or ip.is_multicast
        or ip.is_link_local
        or ip == ipaddress.ip_address("255.255.255.255")
        or any(ip in net for net in _LOCAL_NETS if net.version == ip.version)
    )


def _rule_for(group: Group, hub: HubTarget) -> str | None:
    if group.port == hub.port and (hub.host == group.host or hub.host in group.addresses):
        return "hub"
    if group.proto == "tcp" and group.port == 443 and group.host in _PYPI_NAMES:
        return "update-check"
    local = all(_is_private(a) for a in group.addresses)
    if group.port == 53 and group.proto in ("udp", "tcp") and local:
        return "dns"
    if group.proto == "udp" and group.port == 5353 and group.addresses <= _MDNS:
        return "mdns"
    if group.proto == "udp" and group.port == 67 and local:
        return "dhcp"
    return None


def label_groups(groups: list[Group], hub: HubTarget) -> list[Row]:
    return [
        Row(
            _rule_for(g, hub),
            g.proto,
            g.host,
            g.port,
            g.flows,
            g.packets,
            g.bytes_out,
            frozenset(g.addresses),
        )
        for g in groups
    ]


def unlisted(rows: list[Row]) -> list[Row]:
    return [r for r in rows if not r.listed]


def passes(rows: list[Row]) -> bool:
    return not unlisted(rows)


# --- rendering --------------------------------------------------------------


def _shown_host(row: Row) -> str:
    if row.rule == "hub":
        return "your hub"
    if row.rule in ("dns", "dhcp"):
        return "your router"
    if row.rule == "mdns":
        return "your network (multicast)"
    if _is_private(row.host):
        return "an address on your own network"
    return f"`{row.host}`"


def render_capture_table(rows: list[Row]) -> str:
    """The detailed table for ``measurements.md``: one row per destination and port.

    Addresses on the household's own network are never written down.
    """
    lines = [
        "| What | Where it goes | Port | Protocol | Flows | Packets | Bytes sent | On the list |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for row in sorted(rows, key=lambda r: (not r.listed, r.rule or "", r.host, r.port)):
        what = ALLOWED_BY_ID[row.rule].what if row.rule else "**not on the list**"
        lines.append(
            f"| {what} | {_shown_host(row)} | {row.port or 'n/a'} | {row.proto} | {row.flows} "
            f"| {row.packets} | {row.bytes_out} | {'yes' if row.listed else 'no'} |"
        )
    if len(lines) == 2:
        lines.append("| nothing | nowhere | n/a | n/a | 0 | 0 | 0 | yes |")
    return "\n".join(lines) + "\n"


_EXPECTED_SOURCE = (
    "These rows are the design's allowed list. No capture has been taken yet: the unit "
    "has not arrived, and a capture replaces this line when it has."
)


def render_page_block(rows: list[Row] | None, *, source: str | None = None) -> str:
    """The generated block of the privacy page: the allowed rules, or those a capture saw."""
    if rows is None:
        rules = list(ALLOWED)
        source = source or _EXPECTED_SOURCE
    else:
        seen = {r.rule for r in rows}
        rules = [rule for rule in ALLOWED if rule.id in seen]
        source = source or "These rows come from a capture."
    lines = [
        PAGE_BEGIN,
        source,
        "",
        "| What | Where it goes | When it happens | Leaves your home |",
        "|---|---|---|---|",
    ]
    for rule in rules:
        leaves = "Only on a click" if rule.scope == "internet" else "No"
        lines.append(f"| {rule.what} | {rule.where} | {rule.when} | {leaves} |")
    lines += [PAGE_END, ""]
    return "\n".join(lines)


def _split_page(text: str) -> tuple[str, str, str]:
    start, end = text.find(PAGE_BEGIN), text.find(PAGE_END)
    if start < 0 or end < start:
        raise ValueError("the page has no egress-table markers")
    end += len(PAGE_END)
    return text[:start], text[start:end], text[end:].lstrip("\n")


def page_diff(page_text: str, block: str) -> list[str]:
    """Unified diff of the page's generated block against ``block``; empty when equal."""
    _head, current, _tail = _split_page(page_text)
    return list(
        difflib.unified_diff(
            current.splitlines(),
            block.rstrip("\n").splitlines(),
            fromfile="page",
            tofile="generator",
            lineterm="",
        )
    )


def replace_page_block(page_text: str, block: str) -> str:
    head, _current, tail = _split_page(page_text)
    return head + block.rstrip("\n") + "\n" + ("\n" + tail if tail else "")


# --- capturing --------------------------------------------------------------


class CaptureUnavailable(RuntimeError):
    """This machine cannot sniff packets (not Linux, or no privilege)."""


def capture_tcpdump(
    interface: str,
    out: Path,
    *,
    seconds: float,
    popen: Callable = subprocess.Popen,
    sleep: Callable[[float], None] = time.sleep,
) -> Path:
    """Run ``tcpdump`` on ``interface`` for ``seconds`` and write the pcap to ``out``."""
    cmd = ["tcpdump", "-i", interface, "-n", "-U", "-s", "512", "-w", str(out)]
    try:
        proc = popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except FileNotFoundError as err:
        raise RuntimeError("tcpdump is not installed on this machine") from err
    sleep(seconds)
    proc.send_signal(signal.SIGINT)
    proc.wait(timeout=10)
    return out


def _write_pcap(path: Path, frames: list[tuple[float, bytes]]) -> None:
    out = bytearray(struct.pack("<IHHiIII", 0xA1B2C3D4, 2, 4, 0, 0, 65535, _LINK_ETHERNET))
    for ts, frame in frames:
        out += struct.pack("<IIII", int(ts), int((ts % 1) * 1e6), len(frame), len(frame)) + frame
    path.write_bytes(bytes(out))


class LoopbackCapture:
    """Sniff the loopback interface for traffic on chosen ports (Linux, root)."""

    def __init__(self, ports: set[int]):
        self.ports = ports
        self.frames: list[tuple[float, bytes]] = []
        self._stop = threading.Event()
        try:
            self._sock = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(3))
            self._sock.bind(("lo", 0))
        except (AttributeError, OSError) as err:
            raise CaptureUnavailable(f"cannot sniff the loopback interface here: {err}") from err
        self._thread = threading.Thread(target=self._run, daemon=True)

    def _run(self) -> None:
        while not self._stop.is_set():
            if not select.select([self._sock], [], [], 0.1)[0]:
                continue
            frame, address = self._sock.recvfrom(65535)
            if address[2] == socket.PACKET_OUTGOING:
                continue  # loopback shows every frame twice; keep the incoming copy
            packet = _decode(0.0, _LINK_ETHERNET, frame)
            if packet and (packet.sport in self.ports or packet.dport in self.ports):
                self.frames.append((time.time(), frame))

    def __enter__(self) -> LoopbackCapture:
        self._thread.start()
        return self

    def __exit__(self, *exc) -> None:
        time.sleep(0.3)  # let the last segments reach the sniffer
        self._stop.set()
        self._thread.join(timeout=2)
        self._sock.close()


@dataclass(frozen=True)
class Rehearsal:
    pcap: Path
    hub: HubTarget
    stray_port: int | None


def _listener() -> socket.socket:
    server = socket.socket()
    server.bind(("127.0.0.1", 0))
    server.listen(4)
    return server


def _serve(server: socket.socket, stop: threading.Event) -> None:
    server.settimeout(0.1)
    while not stop.is_set():
        try:
            conn, _ = server.accept()
        except OSError:
            continue
        with conn:
            conn.settimeout(1.0)
            try:
                conn.recv(4096)
                conn.sendall(b"ok")
            except OSError:
                pass


def rehearse(out: Path, *, stray: bool) -> Rehearsal:
    """A fake hub, and optionally a fake stray endpoint, both on loopback.

    Real sockets, really captured; the robot is this process and nothing
    here proves anything about a robot. It proves the pipeline end to end:
    capture, parse, group, label, fail.
    """
    hub_server, stray_server = _listener(), _listener()
    hub_port, stray_port = hub_server.getsockname()[1], stray_server.getsockname()[1]
    stop = threading.Event()
    threads = [
        threading.Thread(target=_serve, args=(s, stop), daemon=True)
        for s in (hub_server, stray_server)
    ]
    try:
        with LoopbackCapture({hub_port, stray_port}) as sniffer:
            for t in threads:
                t.start()
            targets = [hub_port] + ([stray_port] if stray else [])
            for port in targets:
                with socket.create_connection(("127.0.0.1", port), timeout=2) as client:
                    client.sendall(b"rehearsal" * 20)
                    client.recv(16)
    finally:
        stop.set()
        for t in threads:
            if t.is_alive():
                t.join(timeout=2)
        hub_server.close()
        stray_server.close()
    _write_pcap(out, sniffer.frames)
    return Rehearsal(out, HubTarget("127.0.0.1", hub_port), stray_port if stray else None)
